server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations: /app/config/shared/{label}
  application:
    name: config
  profiles:
    active: native
logging.file: /app/logs/${spring.application.name}.log

