version: '3.3'
services:
  user-service:
    ports:
      - ${USER_SERVICE_DEBUG_PORT}:${JAVA_DEBUG_PORT}
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${JAVA_DEBUG_PORT}"
    restart: "no"
  dictionary-service:
    ports:
      - ${DICTIONARY_SERVICE_DEBUG_PORT}:${JAVA_DEBUG_PORT}
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${JAVA_DEBUG_PORT}"
    restart: "no"