version: '3.3'
services:
  registry:    
    image: ${APP_GROUP_ID}/registry:${APP_VERSION}
    ports:
      - 8761:8761
    depends_on:
      - config
    restart: unless-stopped
  config:     
    image: ${APP_GROUP_ID}/config:${APP_VERSION}
    ports:
      - 8888:8888
    restart: unless-stopped
  user-service:
      image: ${APP_GROUP_ID}/user-service:${APP_VERSION}
      ports:
        - 8801:8801
      depends_on:
        - config
        - registry
      restart: unless-stopped
  gateway:
      image: ${APP_GROUP_ID}/gateway:${APP_VERSION}
      ports:
        - 8900:8900
      depends_on:
        - config
        - registry
      restart: unless-stopped
  monitoring:
      image: ${APP_GROUP_ID}/monitoring:${APP_VERSION}
      ports:
        - 8800:8800
      depends_on:
        - config
        - registry
      restart: unless-stopped