version: '3.3'
services:
  registry:    
    image: com.microdemo/registry:${APP_VERSION}
    ports:
      - 8761:8761
    depends_on:
      - config
    restart: unless-stopped
  config:     
    image: com.microdemo/config:${APP_VERSION}
    ports:
      - 8888:8888
    restart: unless-stopped
  user-service:
      image: com.microdemo/user-service:${APP_VERSION}
      ports:
        - 8801:8801
      depends_on:
        - config
        - registry
      restart: unless-stopped
  gateway:
      image: com.microdemo/gateway:${APP_VERSION}
      ports:
        - 8900:8900
      depends_on:
        - config
        - registry
      restart: unless-stopped
  monitoring:
      image: com.microdemo/monitoring:${APP_VERSION}
      ports:
        - 8800:8800
      depends_on:
        - config
        - registry
      restart: unless-stopped