version: '3.3'
services:
  registry:    
    image: com.microdemo/registry:0.0.2-SNAPSHOT   
    ports:
      - 8761:8761
    depends_on:
      - config
  config:     
    image: com.microdemo/config:0.0.2-SNAPSHOT
    ports:
      - 8888:8888
  user-service:
      image: com.microdemo/user-service:0.0.2-SNAPSHOT
      ports:
        - 8801:8801
      depends_on:
        - config
        - registry