logging:
  level:
    org.springframework.security: INFO
management:
  endpoint:
    configprops:
      enabled: true
  endpoints:
    web:
      exposure:
        include: configprops, info, health, metrics, env, hystrix.stream, routes, filters
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
    healthcheck:
      enabled: true
spring:
  jpa:
    show-sql: true