logging:
  level:
    org.springframework.security: INFO
    com.microdemo: DEBUG
management:
  endpoint:
    configprops:
      enabled: true
  endpoints:
    web:
      exposure:
        include: configprops, info, health, metrics, env, hystrix.stream, routes, filters
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
    healthcheck:
      enabled: true
spring:
  jpa:
    show-sql: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false